### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [viviekin/f1-3-c2p1-colmar-academy#5]
Grade: Approaching Satisfactory

Summary: You have a good start to this project. Both the mobile and desktop have correct layouts, they just require some adjustments and finishing touches. Take a look at the issues I created for some tips that will make your life a bit easier. I think you should just spend some more time on this project and really use dev tools to help you debug those trouble spots.
Well done, I hope you enjoyed the course!

**Comment by viviekin** [comment]
Thank you for the advice and feedback!
